version: "3.9"
services:
  app-server:
    build:
      context: .
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - dbpostgres
    networks:
      - backend

  dbpostgres:
    image: postgres:13
    ports:
      - "5432:5432"
    command: postgres -c 'max_connections=500'
    environment:
      POSTGRES_USER: multimodule_project_app
      POSTGRES_PASSWORD: anna123
    volumes:
      - ./pg-scripts:/docker-entrypoint-initdb.d
      - ./db-scripts:/docker-entrypoint-initdb.d
    networks:
      - backend

networks:
  backend:

volumes:
  postgres: