version: "3.9"
services:
  app-server:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - dbpostgres
    networks:
      - backend
      - frontend

  app-client:
    build:
      context: frontend
      dockerfile: ../react-app/Dockerfile
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend

  dbpostgres:
    image: postgres:13
    ports:
      - "5432:5432"
    command: postgres -c 'max_connections=500'
    environment:
      POSTGRES_USER: multimodule_project_app
      POSTGRES_PASSWORD: anna123
    volumes:
      - ./pg-scripts:/docker-entrypoint-initdb.d
    networks:
      - backend

networks:
  backend:
  frontend:

volumes:
  postgres: