spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
    url: jdbc:postgresql://localhost:5432/multimodule_project
    username: postgres
    password: anna123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  token:
    secret: jwtappsecretkey
    expired: 3600000